services:
  waved:
    build: ./ui
    image: waved
  wave_app:
    build: ./ui/wave_app
    image: wave_app
    links:
      - waved
    depends_on:
      - waved
  # api:
  #   build: ./api_service
  #   image: api_service